spring.application.name=Wiem-BenMsahel-4DS9-TP

server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/Wiem_BM_4DS9_TPSKISTATION?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


